use_frameworks!

platform :ios, '10.0'

target 'AAReachability_Example' do
  pod 'AAReachability', :path => '../'

  target 'AAReachability_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
